### PR TITLE
Remove unused methods after review

### PR DESCRIPTION
**Pull request by mrosanes**
Remove unused methods after review for Param Repeats new
interface.

### CODE REVIEW

**Comment by mrosanes** [comment]
Hi Teresa, 

I have done some modifications that should be added in the param repeat implementation if you think this is convenient.

The most important is the commit 'Fix bug when calling macros without parameters'. 
We have seen that macros as 'lsm' did not work after the changes that we proposed in the new implementation. This commit should fix it, and hopefully not break anything else.
Please could you review it and check if it correct?

**Comment by teresanunez** [comment]
Hi Marc,
               thanks for the modifications. I have checked it and it works fine. The only thing, you have
 left a:

print(par)

in the file spockms.py, I guess we don't want to have this print out there. In that case, could you remove it and then I will merge the request?. Many thanks.

**Comment by mrosanes** [comment]
Sure, I forgot the print there.

Done

**Comment by mrosanes** [comment]
Teresa, do not merge it yet; I have seen that macros with one argument does not work (ex: ct 1)
I'll check it and I tell you something.

**Comment by teresanunez** [comment]
... sorry, I have checked many complicated examples ... but not such a simple one ...

**Comment by mrosanes** [comment]
Don't worry, it is our fault; it worked with your changes, and it does not work after our modifications; I have found a solution, but Zibi would like to have a deeper look; we let you know afterward.

**Pull request closed without merging**
